### PR TITLE
Issue #14

### PR DESCRIPTION
**Pull request by Aaryan8751**
Structured the Src Folder

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
@Aaryan8751 Appreciate your time,
You can do much better, like routes folder, containers, components, actions, reducers, etc...
Please improve further. #14

**Comment by Aaryan8751** [comment]
@AkbarHabeeb is there anything more that I need to change?

**Comment by AkbarHabeeb** [comment]
> @AkbarHabeeb is there anything more that I need to change?

Ack

**Comment by Aaryan8751** [comment]
@AkbarHabeeb done

**Comment by AkbarHabeeb** [comment]
This is not a proper way to do it @Aaryan8751 I suggest you to refer some react repo. Thanks, keep learning

**Pull request closed without merging**
