### PR TITLE
Added CONTRIBUTING.md and demo images to Asset folder

### LINKED ISSUE #5: Add Contribution guidelines.
### Add ```CONTRIBUTING.md``` File

As this project is a part of an Open Source Program ```NJACK Winter of Code``` I would recommend to have a contribution guidelines file (```CONTRIBUTING.md```) to assist beginners to get started with open source contribution.

Points to be covered in the guideline :
- How to pull your first request.
- How to create issue.
- Some general rules to keep in mind while contributing to an open source project.
- Links of some tutorials which will help beginners to learn the basics of git and github.

### PR DESCRIPTION
**Pull request by Pranav016**
## Description
Added CONTRIBUTING.md and demo images to Asset folder

Fixes #5 

## Type of change
- [x] New feature
- [x] Documentation Update

## Checklist:
- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Pranav016** [comment]
Please review this PR @AkbarHabeeb . Thanks :)

**Comment by AkbarHabeeb** [comment]
Planned to review tonight, thanks for your patience.

**Comment by AkbarHabeeb** [comment]
Looks good, Merging @Pranav016 
Keep the good work going :)

**Comment by Pranav016** [comment]
> Looks good, Merging @Pranav016
Thank you!

> Keep the good work going :)
You too 😄

**Comment by Pranav016** [comment]
@AkbarHabeeb Please update the points on the NJACK leaderboard as well, Thanks👍

**Comment by AkbarHabeeb** [comment]
Done 👍  Keep going

**Comment by Pranav016** [comment]
> Done 👍 Keep going

My points did not update on the leaderboard, can you plz look into it :)

**Comment by AkbarHabeeb** [comment]
I have updated the points for you already @Pranav016 
When I saw it was 70, then I change it as 75 -> 77 -> 84(5+2)
Hope it clears

**Comment by Pranav016** [comment]
> I have updated the points for you already @Pranav016
> When I saw it was 70, then I change it as 75 -> 77 -> 84(5+2)
> Hope it clears
> 
> Now Im not sure why it turned down to 72, we didn't revoke any changes

Thank you for your help, I'll ask the organizers to fix it. 😊

**Pull request merged**
