### PR TITLE
Adding pull request template

### PR DESCRIPTION
**Pull request by Kerveyfelix**
Fixes issue #12 
Please review my PR.

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
Looking good, Merging it @Kerveyfelix

**Comment by AkbarHabeeb** [comment]
Added the points in NWoC table, please check the other issues which you would like to solve.

**Comment by Kerveyfelix** [comment]
Thank you. I also opened this issue. So if you consider it as the valid opening issue could your give 2 points for opening issue as well?

**Comment by AkbarHabeeb** [comment]
Cool, :) done.

**Pull request merged**
