### PR TITLE
Adding Contributors in README.md file

### PR DESCRIPTION
**Pull request by Kerveyfelix**
### What is the change?
README.md file. Fixes issue #23 

### What does it fix/add?
Add contributors names and github profile link.

### How was it tested?
Using visual studio code

## Submissions guide:
- [ Y] Have you followed the [Contribution guide](https://github.com/Team-Tomato/QP-Generator/blob/master/CONTRIBUTING.md)?
- [ Y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Team-Tomato/QP-Generator/pulls) for the same update/change?
- [ Y] Have you made corresponding changes to the documentation?
- [Y ] Your submission doesn't break any existing feature.
- [ Y] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
#23 Can you make it dynamic, we cant change the contributors in readme every time @Kerveyfelix 
Appreciate your time and work.

**Comment by Kerveyfelix** [comment]
Got the point. Can I work on something that add contributors name dynamically? I can do research about this and make the required changes.

**Comment by codewithvk** [comment]
@Kerveyfelix @AkbarHabeeb 
[this](https://github.com/all-contributors/all-contributors) will surely help you.

**Comment by AkbarHabeeb** [comment]
You can make it dynamic for the same ticket @Kerveyfelix

**Comment by Kerveyfelix** [comment]
Thank you @codewithvk. The link is very helpful.
@AkbarHabeeb Yes, I will.

**Comment by AkbarHabeeb** [comment]
No need for now, lets concentrate on code base. Thanks all.

**Pull request closed without merging**
