### PR TITLE
logo changed

### PR DESCRIPTION
**Pull request by rsrkpatwari1234**
### What is the change?
Url title changed and logo added

### What does it fix/add?
Fixing #68

### Screenshots (if appropriate):
logo

### CODE REVIEW

**Comment by rsrkpatwari1234** [comment]
@AkbarHabeeb please review  my PR and assign me the required scores

**Comment by rsrkpatwari1234** [comment]
@AkbarHabeeb please review by PR and assign me the required scores

**Comment by AkbarHabeeb** [comment]
@rsrkpatwari1234 Looking good will merge tonight

**Comment by rsrkpatwari1234** [comment]
Hello @AkbarHabeeb ,please merge the PR today if possible

**Comment by rsrkpatwari1234** [comment]
Hey @AkbarHabeeb ,please merge my PR and assign me the scores.Tomorrow is the last date,please do it today else I may miss the top contributors list. Thank you

**Comment by AkbarHabeeb** [comment]
Sorry for the delay, the title was ok, can you please ignore the image (leave it blank for now) @rsrkpatwari1234

**Comment by AkbarHabeeb** [comment]
Completed #77

**Pull request closed without merging**
